---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Add hosts to scan
  shell: "omp --xml='<create_target><name>{{ item.address }}</name><hosts>{{ item.address }}</hosts></create_target>'"
  with_items: openvas_targets
  when: openvas_targets is defined
  tags:
    - openvas-scan-configure

- name: Derive the config_uuid
  shell: "omp --get-configs | awk '/Full and fast$/ {print $1}'"
  when: openvas_targets is defined
  register: config_uuid
  tags:
    - openvas-scan-configure

- name: Derive the target_uuid
  shell: "omp --get-targets | awk '/{{ item.address }}/ {print $1}'"
  with_items: openvas_targets
  when: openvas_targets is defined
  register: target_uuid
  tags:
    - openvas-scan-configure

- name: Create a scan task for each target or use the existing one
  shell: "(omp --get-tasks | grep '{{ item.item.address }}' || omp --config={{ config_uuid.stdout }} --create-task --name 'Scan for {{ item.item.address }}' --target={{ item.stdout }}) | awk '{print $1}' | head -n 1"
  with_items: target_uuid.results
  when: openvas_targets is defined
  register: task_uuid
  tags:
    - openvas-scan-configure

- name: Start the scan
  shell: "omp --start-task {{ item.stdout }}"
  with_items: task_uuid.results
  when: openvas_targets is defined
  tags:
    - openvas-scan-configure

